# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import doWork_pb2 as doWork__pb2


class SimulateServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DoWork = channel.unary_unary(
                '/doWork.SimulateService/DoWork',
                request_serializer=doWork__pb2.Message.SerializeToString,
                response_deserializer=doWork__pb2.Message.FromString,
                )


class SimulateServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def DoWork(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SimulateServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DoWork': grpc.unary_unary_rpc_method_handler(
                    servicer.DoWork,
                    request_deserializer=doWork__pb2.Message.FromString,
                    response_serializer=doWork__pb2.Message.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'doWork.SimulateService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SimulateService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def DoWork(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/doWork.SimulateService/DoWork',
            doWork__pb2.Message.SerializeToString,
            doWork__pb2.Message.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
