// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.12.3
// source: do_work.proto

package doWork

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Body string `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
}

func (x *Message) Reset() {
	*x = Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_do_work_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_do_work_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_do_work_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

var File_do_work_proto protoreflect.FileDescriptor

var file_do_work_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x64, 0x6f, 0x5f, 0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x06, 0x64, 0x6f, 0x57, 0x6f, 0x72, 0x6b, 0x22, 0x1d, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x32, 0x40, 0x0a, 0x0f, 0x53, 0x69, 0x6d, 0x75, 0x6c, 0x61,
	0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x2d, 0x0a, 0x07, 0x64, 0x6f, 0x5f,
	0x77, 0x6f, 0x72, 0x6b, 0x12, 0x0f, 0x2e, 0x64, 0x6f, 0x57, 0x6f, 0x72, 0x6b, 0x2e, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x0f, 0x2e, 0x64, 0x6f, 0x57, 0x6f, 0x72, 0x6b, 0x2e, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x00, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_do_work_proto_rawDescOnce sync.Once
	file_do_work_proto_rawDescData = file_do_work_proto_rawDesc
)

func file_do_work_proto_rawDescGZIP() []byte {
	file_do_work_proto_rawDescOnce.Do(func() {
		file_do_work_proto_rawDescData = protoimpl.X.CompressGZIP(file_do_work_proto_rawDescData)
	})
	return file_do_work_proto_rawDescData
}

var file_do_work_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_do_work_proto_goTypes = []interface{}{
	(*Message)(nil), // 0: doWork.Message
}
var file_do_work_proto_depIdxs = []int32{
	0, // 0: doWork.SimulateService.do_work:input_type -> doWork.Message
	0, // 1: doWork.SimulateService.do_work:output_type -> doWork.Message
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_do_work_proto_init() }
func file_do_work_proto_init() {
	if File_do_work_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_do_work_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_do_work_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_do_work_proto_goTypes,
		DependencyIndexes: file_do_work_proto_depIdxs,
		MessageInfos:      file_do_work_proto_msgTypes,
	}.Build()
	File_do_work_proto = out.File
	file_do_work_proto_rawDesc = nil
	file_do_work_proto_goTypes = nil
	file_do_work_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// SimulateServiceClient is the client API for SimulateService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SimulateServiceClient interface {
	DoWork(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Message, error)
}

type simulateServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSimulateServiceClient(cc grpc.ClientConnInterface) SimulateServiceClient {
	return &simulateServiceClient{cc}
}

func (c *simulateServiceClient) DoWork(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Message, error) {
	out := new(Message)
	err := c.cc.Invoke(ctx, "/doWork.SimulateService/do_work", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SimulateServiceServer is the server API for SimulateService service.
type SimulateServiceServer interface {
	DoWork(context.Context, *Message) (*Message, error)
}

// UnimplementedSimulateServiceServer can be embedded to have forward compatible implementations.
type UnimplementedSimulateServiceServer struct {
}

func (*UnimplementedSimulateServiceServer) DoWork(context.Context, *Message) (*Message, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DoWork not implemented")
}

func RegisterSimulateServiceServer(s *grpc.Server, srv SimulateServiceServer) {
	s.RegisterService(&_SimulateService_serviceDesc, srv)
}

func _SimulateService_DoWork_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Message)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SimulateServiceServer).DoWork(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/doWork.SimulateService/DoWork",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SimulateServiceServer).DoWork(ctx, req.(*Message))
	}
	return interceptor(ctx, in, info, handler)
}

var _SimulateService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "doWork.SimulateService",
	HandlerType: (*SimulateServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "do_work",
			Handler:    _SimulateService_DoWork_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "do_work.proto",
}
